# Generated by Django 5.2.4 on 2025-07-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maxMin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "idCliente",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("pais", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=200)),
                (
                    "tipoCliente",
                    models.CharField(default="Cliente Nuevo", max_length=20),
                ),
                ("numTransacciones", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": '"administracion"."clientes"',
            },
        ),
        migrations.CreateModel(
            name="Caducidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaCaducidad", models.DateField()),
                ("cantidad", models.IntegerField()),
                (
                    "productoId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productoCaducidad",
                        to="maxMin.productos",
                    ),
                ),
            ],
            options={
                "db_table": '"produccionLogistica"."caducidades"',
            },
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "idVenta",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateTimeField()),
                ("paisVenta", models.CharField(max_length=100)),
                ("estadoVenta", models.CharField(max_length=100)),
                ("ciudadVenta", models.CharField(max_length=200)),
                ("unidad", models.CharField(max_length=20)),
                ("vendedor", models.CharField(max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasCliente",
                        to="reporteVentas.clientes",
                    ),
                ),
            ],
            options={
                "db_table": '"administracion"."ventas"',
            },
        ),
        migrations.CreateModel(
            name="VentasPVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("cantidad", models.BigIntegerField()),
                (
                    "idInsumo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVInsumos",
                        to="maxMin.insumos",
                    ),
                ),
                (
                    "idProducto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVProducto",
                        to="maxMin.productos",
                    ),
                ),
            ],
            options={
                "db_table": '"produccionLogistica"."ventasPVA"',
            },
        ),
        migrations.CreateModel(
            name="VentasPVH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=50)),
                ("categoria", models.CharField(default="", max_length=100)),
                ("cantidad", models.BigIntegerField()),
                (
                    "precioUnitario",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "idVenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVVenta",
                        to="reporteVentas.ventas",
                    ),
                ),
            ],
            options={
                "db_table": '"administracion"."ventasPVH"',
            },
        ),
    ]
